#!/usr/bin/env bash
#
# Build the Linux packages for one architecture from the tarball build-release.sh produced.
#
#   scripts/package-linux.sh <goarch> [version] [distdir]
#
# Produces boks_<version>_<arch>.deb and boks-<version>-1.<arch>.rpm, each with a .sha256.
#
# Both are built with the distribution's own tools — dpkg-deb and rpmbuild — rather than
# with a packaging binary fetched from the internet. That is not stylistic: this project
# refuses unpinned downloads everywhere else, and a release pipeline that curls a tool to
# build the thing it is asking people to trust would be the one place it made an exception.
#
# What these packages contain is *the CLI*, and nothing else. See the Description field
# below, and docs/install.md, for why: the rest of the stack is either not packaged for
# Linux at all (nerdbox) or is too old in every distribution that has it (containerd).
set -euo pipefail

goarch="${1:?usage: package-linux.sh <goarch> [version] [distdir]}"

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
version="${2:-$("$root/scripts/image-tag.sh")}"
dist="${3:-$root/dist}"

case "$goarch" in
amd64) rpmarch=x86_64 ;;
arm64) rpmarch=aarch64 ;;
*)
	echo "unsupported architecture: $goarch" >&2
	exit 1
	;;
esac

tarball="$dist/boks_${version}_linux_${goarch}.tar.gz"
[ -f "$tarball" ] || {
	echo "missing $tarball; run scripts/build-release.sh linux $goarch first" >&2
	exit 1
}

if [ -z "${SOURCE_DATE_EPOCH:-}" ]; then
	SOURCE_DATE_EPOCH="$(git -C "$root" log -1 --format=%ct 2>/dev/null || echo 0)"
fi
export SOURCE_DATE_EPOCH

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

tar -xzf "$tarball" -C "$work"
extracted="$work/boks_${version}_linux_${goarch}"

# The completion scripts are architecture-independent — they are text the CLI prints — so
# they are generated once with a binary built for whatever host is doing the packaging,
# and shipped in every package. Generating them from the *target* binary would mean being
# able to execute it, which cross-building deliberately does not require.
completions="$work/completions"
mkdir -p "$completions"
gen="$work/boks-host"
CGO_ENABLED=0 go build -trimpath -o "$gen" "$root/cmd/boks"
"$gen" completion bash >"$completions/boks"
"$gen" completion zsh >"$completions/_boks"
"$gen" completion fish >"$completions/boks.fish"

# --- the shared payload -------------------------------------------------------------
# One tree, installed identically by both package formats, so a bug in the layout is a bug
# in one place.
stage_payload() {
	local dest="$1"
	install -Dm0755 "$extracted/boks" "$dest/usr/bin/boks"
	install -Dm0644 "$extracted/LICENSE" "$dest/usr/share/doc/boks/copyright"
	install -Dm0644 "$extracted/README.md" "$dest/usr/share/doc/boks/README.md"
	install -Dm0644 "$completions/boks" "$dest/usr/share/bash-completion/completions/boks"
	install -Dm0644 "$completions/_boks" "$dest/usr/share/zsh/vendor-completions/_boks"
	install -Dm0644 "$completions/boks.fish" "$dest/usr/share/fish/vendor_completions.d/boks.fish"
}

# --- .deb ---------------------------------------------------------------------------
deb_root="$work/deb"
stage_payload "$deb_root"
mkdir -p "$deb_root/DEBIAN"
cat >"$deb_root/DEBIAN/control" <<EOF
Package: boks
Version: ${version}
Architecture: ${goarch}
Maintainer: Dag Sommer <dagsommer@users.noreply.github.com>
Section: devel
Priority: optional
Homepage: https://github.com/dagsommer/boks
Recommends: erofs-utils
Description: run coding agents in isolated microVMs, locally
 Boks runs coding agents and other untrusted developer tooling inside a microVM
 per sandbox, on your own machine. No account, no cloud service, no telemetry.
 .
 This package contains the boks CLI and nothing else. Starting a sandbox also
 needs containerd 2.2 or later, the containerd-shim-nerdbox-v1 runtime shim,
 libkrun 1.18 or later, and mkfs.erofs from erofs-utils 1.8 or later. Only the
 last of those is packaged for Debian and Ubuntu, and 24.04 LTS ships 1.7.1,
 which is too old; nerdbox is packaged by no distribution at all and must be
 built from source. Run "boks doctor" after installing: it checks every one of
 them and prints what to do about each gap.
 .
 Linux is untested end to end. The VM boundary has been verified on macOS on
 Apple silicon only; the Linux/KVM path is designed for and has never been run.
EOF

# --root-owner-group so the package does not depend on the uid that built it, and a fixed
# mtime so two builds of one commit produce identical bytes.
dpkg-deb --root-owner-group --build "$deb_root" \
	"$dist/boks_${version}_${goarch}.deb" >/dev/null

# --- .rpm ---------------------------------------------------------------------------
rpm_root="$work/rpmbuild"
mkdir -p "$rpm_root"/{BUILD,RPMS,SOURCES,SPECS,BUILDROOT}
stage_payload "$work/rpmpayload"

cat >"$rpm_root/SPECS/boks.spec" <<EOF
# Generated by scripts/package-linux.sh. The binary is built by build-release.sh and
# installed here as-is: there is no %build stage, because cross-compiling in Go and
# building an rpm are two jobs and mixing them would mean an rpmbuild per architecture.
%global debug_package %{nil}
%global _build_id_links none
%global __strip /bin/true

Name:           boks
Version:        ${version}
Release:        1
Summary:        Run coding agents in isolated microVMs, locally
License:        Apache-2.0
URL:            https://github.com/dagsommer/boks
Recommends:     erofs-utils

%description
Boks runs coding agents and other untrusted developer tooling inside a microVM
per sandbox, on your own machine. No account, no cloud service, no telemetry.

This package contains the boks CLI and nothing else. Starting a sandbox also
needs containerd 2.2 or later, the containerd-shim-nerdbox-v1 runtime shim,
libkrun 1.18 or later, and mkfs.erofs from erofs-utils 1.8 or later. nerdbox is
packaged by no distribution and must be built from source. Run "boks doctor"
after installing: it checks every one of them and prints what to do about each
gap.

Linux is untested end to end. The VM boundary has been verified on macOS on
Apple silicon only.

%install
cp -a %{_sourcedir}/payload/. %{buildroot}/

%files
%license /usr/share/doc/boks/copyright
/usr/bin/boks
/usr/share/doc/boks/README.md
/usr/share/bash-completion/completions/boks
/usr/share/zsh/vendor-completions/_boks
/usr/share/fish/vendor_completions.d/boks.fish

%changelog
EOF

cp -a "$work/rpmpayload" "$rpm_root/SOURCES/payload"
# --target rather than a BuildArch line in the spec: BuildArch is checked against the build
# host's own architecture, so an aarch64 spec cannot be built on an x86_64 runner and vice
# versa, which is precisely what cross-building a Go binary asks for. --target sets the
# package's architecture without that check.
rpmbuild -bb \
	--define "_topdir $rpm_root" \
	--define "_sourcedir $rpm_root/SOURCES" \
	--target "$rpmarch" \
	"$rpm_root/SPECS/boks.spec" >"$work/rpmbuild.log" 2>&1 ||
	{
		cat "$work/rpmbuild.log" >&2
		exit 1
	}
cp "$rpm_root/RPMS/$rpmarch/boks-${version}-1.${rpmarch}.rpm" "$dist/"

(cd "$dist" && sha256sum "boks_${version}_${goarch}.deb" >"boks_${version}_${goarch}.deb.sha256")
(cd "$dist" && sha256sum "boks-${version}-1.${rpmarch}.rpm" >"boks-${version}-1.${rpmarch}.rpm.sha256")

echo "built $dist/boks_${version}_${goarch}.deb"
echo "built $dist/boks-${version}-1.${rpmarch}.rpm"
